export const tariffLeksikon = {
    A: [
        "AFP – Avtalefestet pensjon",
        "Akkordlønn",
        "Allmenngjøring",
        "Antesipere",
        "Ansiennitet",
        "Ansiennitetsstige",
        "Ansiennitetstillegg",
        "Arbeidsavtale",
        "Arbeidsgiver",
        "Arbeidsgiverforening",
        "Arbeidskamp",
        "Arbeidskontrakt",
        "Arbeidsretten",
        "Arbeidsstans",
        "Arbeidstaker",
        "Arbeidstakerforening",
        "Arbeidstid",
        "Arbeidstvist",
        "Arbeidstvistloven",
        "Avtaleperiode"
    ],
    B: [
        "Bedriftsansiennitet",
        "Beregningsutvalget",
        "Bevegelig lønn",
        "Bevegelige helligdager",
        "Boikott/blokade",
        "Bonus/provisjon",
        "Bruttolønn"
    ],
    D: [
        "Dagsing/gå sakte-aksjon/dagtidsaksjon",
        "Datotillegg",
        "Demonstrasjonsstreik",
        "Direkteavtale",
        "Disponibel reallønn"
    ],
    E: [
        "Etterslep"
    ],
    F: [
        "Fagforbund/forbund",
        "Fagforening",
        "Faste tillegg",
        "Fellesoppgjør",
        "Forbundsvise oppgjør",
        "Forhandlinger",
        "Forhandlingsdelegasjon",
        "Forhandlingsforslag",
        "Forhandlingsrett",
        "Fredsplikt",
        "Frivillig lønnsnemnd",
        "Frontfaget",
        "Frontfagsmodellen"
    ],
    G: [
        "Garantiordning",
        "Garantitillegg",
        "Generelt tillegg",
        "Gratispassasjerer",
        "Glidning",
        "Grunnlønn",
        "Gå sakte-aksjon"
    ],
    H: [
        "Hengeavtale",
        "Horisontal tariffavtale",
        "Hovedavtale",
        "Hovedoppgjør",
        "Hovedorganisasjon",
        "Hovedtariffavtale",
        "Husforening",
        "Hybridpensjon"
    ],
    I: [
        "Indeksregulering",
        "Individuelle tillegg",
        "Innskuddspensjon",
        "Innstillingsrett",
        "Inntekt",
        "Interessetvist"
    ],
    J: [
        "Justeringsoppgjør"
    ],
    K: [
        "Kjøpekraft",
        "Kobling",
        "Kombinert oppgjør",
        "Kommunesektoren/kommunal sektor",
        "Konflikt",
        "Konsumprisindeksen",
        "Kontaktutvalget",
        "Kronetillegg"
    ],
    L: [
        "Landsforening",
        "Lavlønn",
        "Lavlønnsgaranti",
        "Lavlønnstillegg",
        "Levealdersjustering",
        "Likelønn",
        "Likelønnstillegg",
        "Lockout",
        "Lokal særavtale",
        "Lokal forhandlingsrett",
        "Lokale lønnsforhandlinger",
        "Lokale lønnstillegg",
        "Lønn",
        "Lønnsansiennitet",
        "Lønnsglidning",
        "Lønnsmottaker",
        "Lønnsnemnd",
        "Lønnsnemndsloven",
        "Lønnsoppgjør",
        "Lønnsoverheng",
        "Lønnsramme",
        "Lønnsregulativ",
        "Lønnsspenn",
        "Lønnstabell",
        "Lønnstrinn",
        "Lønnstrinnsopprykk",
        "Lønnsstatistikk"
    ],
    M: [
        "Mekling",
        "Meklingsforslag",
        "Mellomoppgjør",
        "Mertid",
        "Mindrelønnsutvikling",
        "Minstelønn/minstelønnssatser",
        "Minstelønnsavtale",
        "Månedslønn"
    ],
    N: [
        "Naturallønn/naturalytelser",
        "Nettolønn",
        "Nominell lønn",
        "Nominelt tillegg",
        "Normallønn",
        "Normallønnsavtale"
    ],
    O: [
        "Obligatorisk tjenestepensjon",
        "Offentlig sektor",
        "Offentlig tjenestepensjon",
        "Omfangsbestemmelser",
        "Oppgjørsform",
        "Oppsigelse av tariffavtale",
        "Organisasjonsfrihet",
        "O/U-ordningen",
        "Overenskomst",
        "Overenskomstområde",
        "Overheng"
    ],
    P: [
        "Partene i arbeidslivet",
        "Passiv lockout",
        "Pendelvoldgift",
        "Permisjon",
        "Permittering",
        "Personlig tillegg",
        "Plassfratredelse",
        "Plassoppsigelse",
        "Politisk streik/demonstrasjonsstreik",
        "Pott",
        "Prestasjonslønn",
        "Privat sektor",
        "Prolongering",
        "Prisoverheng",
        "Prosenttillegg",
        "Protokoll"
    ],
R: [
    "Ramme",
    "Rammeavtale",
    "Realinntekt",
    "Realkompetanse",
    "Reallønn",
    "Reallønnsvekst",
    "Regulativlønn",
    "Rettstvist",
    "Rikslønnsnemnda",
    "Riksmekleren",
    "Rød strek",
    "Røde dager"
],
S: [
    "Samordnet oppgjør",
    "Sentrale oppgjør",
    "Sammensetningseffekt",
    "Sentrale parter",
    "Sit-down-streik",
    "Skiftarbeid",
    "Skisse",
    "Sluttvederlag",
    "Slitertillegg",
    "Spekterområdet",
    "Spekter-forhandlingene",
    "Stillingsbetegnelse",
    "Stillingskode",
    "Streik",
    "Streikebidrag",
    "Streikebryter",
    "Streikefond",
    "Streikevarsel",
    "Slitertillegg",
    "Strukturendringer",
    "Styringsrett",
    "Sympatistreik",
    "Særavtale"
],

    T: [
        "Tariffavgift",
        "Tariffavtale",
        "Tariffhopping",
        "Tariffmessig lønnsøkning",
        "Tariffområde",
        "Tariffoppgjør",
        "Tarifforhandlinger",
        "Tariffpartene",
        "Tariffperiode",
        "Tariffrevisjon",
        "Teknisk beregningsutvalg",
        "Teknisk oppgjør/revisjon",
        "Tidlønn",
        "Tillitsvalgt",
        "Timelønn",
        "Tjenestepensjon",
        "Tjenestetvistloven",
        "Turnus",
        "Tvungen lønnsnemnd",
        "Tvungen mekling"
    ],
    U: [
        "Uenighetsprotokoll",
        "Ufravikelighetsprinsippet",
        "Ulovlig streik",
        "Uravstemning",
        "Utløpsdato"
    ],
    V: [
        "Variable tillegg",
        "Vertikal tariffavtale",
        "Vill streik",
        "Voldgift"
    ],
    Y: [
        "Ytelsespensjon"
    ],
    Ø: [
        "Økonomisk ramme"
    ],
    Å: [
        "Årslønn",
        "Årslønnsvekst",
        "Årsverk"
    ]
};
